name-template: "$MAJOR 🌈"
version-template: $MAJOR
tag-template: "v$MAJOR"
categories:
  - title: "🚀 Architecture"
    label: "Architecture"
  - title: "☁️ Azure"
    label: "Azure"
  - title: "📅 Data"
    label: "Data"
  - title: "⚙️ Engineering"
    label: "Engineering"
  - title: "🔒 Security"
    label: "Security"
  - title: "🙏 Teams"
    label: "Teams"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  $CHANGES
